name: Validate Formatting
on: [push, pull_request]
jobs:
  validate:
    name: Validate Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"

      - name: Install dependencies
        run: |
          dotnet tool restore

      - name: Validate formatting
        run: |
          dotnet csharpier --check .
