name: Run Tests
on: [push, pull_request]
jobs:
  unit:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x.x"

      - name: Run unit tests
        run: |
          dotnet test Source/Outcome.Tests.Unit/Outcome.Tests.Unit.csproj
